### ISSUE TITLE
broken in docker based warrior, since sudo is unavailable there

### ISSUE THREAD

**Issue by HorayNarea** [ArchiveTeam/telegram-grab#10]
Commit 0eeef780e3cb9b9c36003dd21e818f180a34e916 has broken the docker based warrior, because warrior-install.sh tries to use `sudo`, which is not available, to install a lua library

Edit to clarify:
I mean this warrior: https://wiki.archiveteam.org/index.php?title=ArchiveTeam_Warrior, not the Docker image produced by the Dockerfile inside this repo

**Comment by TheTechRobo** [comment]
I can't reproduce this - the Telegram Warrior project runs fine for me on the Docker-based Warrior.

![image](https://github.com/ArchiveTeam/telegram-grab/assets/52163910/f427b09b-39e6-4951-ac4e-7c7af49c0676)

**Comment by HorayNarea** [comment]
Whoops, sorry… I just realised that the docker warrior image was pretty old and watchtower did not update it because of  a big interval between tries…
I just manually updated and now at least it gets past the install step but still throws an error:

```
Installing lua-utf8...
Installing https://luarocks.org/utf8-1.2-0.src.rock
gcc -O2 -fPIC -I/usr/include/lua5.1 -c lutf8lib.c -o lutf8lib.o
gcc -shared -o utf8.so -L/usr/local/lib lutf8lib.o
utf8 1.2-0 is now installed in /usr/local (license: MIT)


2023-10-27 01:25:53,429 - seesaw.warrior - DEBUG - Result of the install process: True
2023-10-27 01:25:53,429 - seesaw.warrior - DEBUG - Clone project telegram /home/warrior/projects/telegram
2023-10-27 01:25:53,454 - seesaw.warrior - DEBUG - Cloning version 9525e1f
2023-10-27 01:25:53,455 - seesaw.warrior - DEBUG - Load pipeline /home/warrior/data/projects/telegram-9525e1f/pipeline.py
2023-10-27 01:25:53,455 - seesaw.warrior - DEBUG - Pipeline has been read. Begin ConfigValue collection
2023-10-27 01:25:53,455 - seesaw.warrior - DEBUG - Executing pipeline
2023-10-27 01:25:53,707 - seesaw.warrior - ERROR - Error loading pipeline
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 736, in start_selected_project
    (project, pipeline, config_values) = self.load_pipeline(
  File "/usr/local/lib/python3.9/site-packages/seesaw/warrior.py", line 686, in load_pipeline
    exec(pipeline_str, local_context, global_context)
  File "<string>", line 55, in <module>
Exception: No usable Wget+At found.
2023-10-27 01:25:53,708 - seesaw.warrior - WARNING - Project telegram did not install correctly and we're ignoring this problem.
```

**Comment by HorayNarea** [comment]
Huh, after destroying and recreating the whole thing it now works fine… weird :shrug:
